///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class NodeVersionEntity {
  /*
{
  "framework": "x64",
  "version": "v25.9.0",
  "date": "2026-03-31",
  "files": [
    "aix-ppc64"
  ],
  "npm": "11.12.1",
  "v8": "14.1.146.11",
  "uv": "1.51.0",
  "zlib": "1.3.1",
  "openssl": "3.5.5",
  "modules": "141",
  "lts": false,
  "security": false
} 
*/

  String? version;
  String? date;
  List<String>? files;
  String? npm;
  String? v8;
  String? uv;
  String? zlib;
  String? openssl;
  String? modules;
  bool? security;
  String? framework;

  NodeVersionEntity({
    this.version,
    this.date,
    this.files,
    this.npm,
    this.v8,
    this.uv,
    this.zlib,
    this.openssl,
    this.modules,
    this.security,
    this.framework,
  });
  NodeVersionEntity.fromJson(Map<String, dynamic> json) {
    version = json['version']?.toString();
    date = json['date']?.toString();
    if (json['files'] != null) {
      final v = json['files'];
      final arr0 = <String>[];
      v.forEach((v) {
        arr0.add(v.toString());
      });
      files = arr0;
    }
    npm = json['npm']?.toString();
    v8 = json['v8']?.toString();
    uv = json['uv']?.toString();
    zlib = json['zlib']?.toString();
    openssl = json['openssl']?.toString();
    modules = json['modules']?.toString();
    security = json['security'];
    framework = json['framework'];
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['version'] = version;
    data['date'] = date;
    final v = files;
    final arr0 = [];
    for (var v in v!) {
      arr0.add(v);
    }
    data['files'] = arr0;
    data['npm'] = npm;
    data['v8'] = v8;
    data['uv'] = uv;
    data['zlib'] = zlib;
    data['openssl'] = openssl;
    data['modules'] = modules;
    data['security'] = security;
    data['framework'] = framework;
    return data;
  }
}
